Colours = {
    -- Metallic
    metallic_black = 0,
    metallic_graphite = 1,
    metallic_black_steel = 2,
    metallic_dark_silver = 3,
    metallic_silver = 4,
    metallic_blue_silver = 5,
    metallic_steel_gray = 6,
    metallic_shadow_silver = 7,
    metallic_stone_silver = 8,
    metallic_midnight_silver = 9,
    metallic_gun_metal = 10,
    metallic_anthracite_gray = 11,

    metallic_red = 27,
    metallic_torino_red = 28,
    metallic_formula_red = 29,
    metallic_blaze_red = 30,
    metallic_grace_red = 31,
    metallic_garnet_red = 32,
    metallic_desert_red = 33,
    metallic_cabernet_red = 34,
    metallic_candy_red = 35,
    metallic_sunrise_orange = 36,
    metallic_gold = 37,
    metallic_orange = 38,

    metallic_dark_green = 49,
    metallic_racing_green = 50,
    metallic_sea_green = 51,
    metallic_olive_green = 52,
    metallic_bright_green = 53,
    metallic_gasoline_blue = 54,

    metallic_midnight_blue = 61,
    metallic_dark_blue = 62,
    metallic_saxony_blue = 63,
    metallic_blue = 64,
    metallic_mariner_blue = 65,
    metallic_harbor_blue = 66,
    metallic_diamond_blue = 67,
    metallic_surf_blue = 68,
    metallic_nautical_blue = 69,
    metallic_bright_blue = 70,
    metallic_purple_blue = 71,
    metallic_spinnaker_blue = 72,
    metallic_ultra_blue = 73,

    metallic_bright_purple = 81,
    metallic_cream = 107,

    -- Matte
    matte_black = 12,
    matte_gray = 13,
    matte_light_gray = 14,
    matte_ice_white = 131,
    matte_blue = 83,
    matte_dark_blue = 82,
    matte_midnight_blue = 84,
    matte_midnight_purple = 149,
    matte_schafter_purple = 148,
    matte_red = 39,
    matte_dark_red = 40,
    matte_orange = 41,
    matte_yellow = 42,
    matte_lime_green = 55,
    matte_green = 128,
    matte_forest_green = 151,
    matte_foliage_green = 155,

    -- Worn
    worn_black = 21,
    worn_graphite = 22,
    worn_silver_gray = 23,
    worn_silver = 24,
    worn_blue_silver = 25,
    worn_shadow_silver = 26,

    worn_red = 46,
    worn_golden_red = 47,
    worn_dark_red = 48,

    worn_dark_green = 56,
    worn_green = 57,
    worn_sea_wash = 58,

    worn_dark_blue = 59,
    worn_blue = 60,
    worn_light_blue = 74,

    worn_honey_beige = 99,
    worn_brown = 95,
    worn_dark_brown = 96,
    worn_straw_beige = 97,
    worn_sandy_brown = 98,
    worn_off_white = 105,

    -- Metal
    metal_brushed_steel = 117,
    metal_brushed_black_steel = 118,
    metal_brushed_aluminum = 119,
    metal_brushed_gold = 158,
    metal_brushed_pure_gold = 159,

    -- Chrome
    chrome = 120,
}
